### ISSUE TITLE
请问该如何使用呢？

### ISSUE THREAD

**Issue by hmf1235789** [marunemitsu/QTFluent#1]
你好，请问在Qt Creator里面打开，复制到其他ui文件中使用，已经丢失了原有的配色了，而且文件夹内没有qss文件，如果使用这个模板呢？

**Comment by marunemitsu** [comment]
QT Creater右上角的层级页面里面，在MainWindow上右键，查看qss代码然后复制粘贴给新的ui文件就可以了。

**Comment by marunemitsu** [comment]
针对不同的控件也有不同的qss属性分配，所以推荐在复制的时候也同步复制过去相应的qss配置哦。
